# This is a basic workflow that is manually triggered

name: Build_Documents

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:  
  # This workflow contains a single job called "greet"
  build-html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Building HTML"
  build-pdf:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Building PDF"
    
